export const normalizeInvoiceResponse = (doc) => ({
  invoiceId: doc.invoiceId || `INV-${Date.now()}`,
  items: doc.items || [],
  gst: doc.gst || 0,
  totalNetAmount: doc.totalNetAmount || 0,
  totalNetAmountAfterDiscount: doc.totalNetAmountAfterDiscount || 0,
  totalDiscount: doc.totalDiscount || 0,
  totalTaxAmount: doc.totalTaxAmount || 0,
  globalDiscount: doc.globalDiscount || 0,
  globalDiscountType: doc.globalDiscountType || "",
  roundOff: doc.roundOff || false,
  roundOffAmount: doc.roundOffAmount || 0,
  grandTotal: doc.grandTotal || doc.total || 0,
  shippingCharges: doc.shippingCharges || 0,
  amountPaid: doc.amountPaid || 0,
  partialPaid: doc.partialPaid || 0,
  paymentStatus: doc.paymentStatus || "Pending",
  paymentMode: doc.paymentMode || "Pending",
  invoiceDate: doc.invoiceDate || new Date(),
  paymentDate: doc.paymentDate || null,
  notes: doc.notes || "",
  sendSMS: doc.sendSMS || false,
  _id: doc._id,
  paymentHistory: doc.paymentHistory || [],
  createdAt: doc.createdAt,
  updatedAt: doc.updatedAt,
  __v: doc.__v,
  pdfUrl: doc.pdfUrl || null, // ✅ ensure this key is present
});
