import { uniqueId } from "./calculations";

export const createBoardTable = () => ({
  id: uniqueId(),
  rows: [
    {
      sNo: "01",
      productCode: "P-09977",
      productName: "Flex Sign Board",
      productDescription: "Product Description",
      thickness: "12",
      lengthInch: "4",
      lengthFt: "0",
      heightInch: "4",
      heightFt: "0",
      size: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
    {
      sNo: "02",
      productCode: "P-09977",
      productName: "Abc Sign Board",
      productDescription: "Product Description",
      thickness: "12",
      lengthInch: "4",
      lengthFt: "0",
      heightInch: "4",
      heightFt: "0",
      size: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
    {
      sNo: "03",
      productCode: "P-09977",
      productName: "Xyz Sign Board",
      productDescription: "Product Description",
      thickness: "12",
      lengthInch: "4",
      lengthFt: "0",
      heightInch: "4",
      heightFt: "0",
      size: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
  ],
});

export const createLetterTable = () => ({
  id: uniqueId(),
  rows: [
    {
      sNo: "01",
      productCode: "P-09977",
      productName: "Flex Sign Letter",
      productDescription: "Product Description",
      letters: "A,B,C",
      thickness: "12",
      length: "4",
      height: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
    {
      sNo: "",
      productCode: "",
      productName: "",
      productDescription: "",
      letters: "A,B,C",
      thickness: "12",
      length: "4",
      height: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
    {
      sNo: "",
      productCode: "",
      productName: "",
      productDescription: "",
      letters: "A,B,C",
      thickness: "12",
      length: "4",
      height: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
  ],
});

export const createBoardLetterTable = () => ({
  id: uniqueId(),
  productRow: {
    sNo: "01",
    productCode: "P-09977",
    productName: "Flex Sign Board",
    productDescription: "Product Description",
    board: "12",
    thickness: "1",
    lengthInch: "4",
    lengthFt: "0",
    heightInch: "12",
    heightFt: "0",
    size: "2",
    quantity: "23",
    rate: "2354",
    amount: "2354",
    lsp: "",
  },
  letterRows: [
    {
      letters: "A,B,C",
      thickness: "12",
      length: "4",
      height: "4",
      size: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
    {
      letters: "A,B,C",
      thickness: "12",
      length: "4",
      height: "4",
      size: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
    {
      letters: "A,B,C",
      thickness: "12",
      length: "4",
      height: "4",
      size: "4",
      quantity: "2",
      rate: "12",
      amount: "200",
      lsp: "",
    },
  ],
});
