// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
                          //       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   // static const FirebaseOptions web = FirebaseOptions(
//   //   apiKey: 'AIzaSyBMj9gHTStt99bM0fwjM1JtCF5xx--B3J4',
//   //   appId: '1:653542564864:web:4f0746adf1116ae2c724e5',
//   //   messagingSenderId: '653542564864',
//   //   projectId: 'dss-crm-f4669',
//   //   authDomain: 'dss-crm-f4669.firebaseapp.com',
//   //   storageBucket: 'dss-crm-f4669.firebasestorage.app',
//   //   measurementId: 'G-BE6GFHMJG7',
//   // );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDqa3W53htP1ge3_5hRjWObg2vfH6wbqiQ',
//     appId: '1:653542564864:android:50eef7a7d1ca870dc724e5',
//     messagingSenderId: '653542564864',
//     projectId: 'dss-crm-f4669',
//     storageBucket: 'dss-crm-f4669.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCxW0bdBfgKNypEbwsCGcblrp_3FvCBxaM',
//     appId: '1:653542564864:ios:1866a106a213947ac724e5',
//     messagingSenderId: '653542564864',
//     projectId: 'dss-crm-f4669',
//     storageBucket: 'dss-crm-f4669.firebasestorage.app',
//     iosBundleId: 'com.codecrafter.dsscrm',
//   );
//
//   // static const FirebaseOptions macos = FirebaseOptions(
//   //   apiKey: 'AIzaSyCxW0bdBfgKNypEbwsCGcblrp_3FvCBxaM',
//   //   appId: '1:653542564864:ios:1866a106a213947ac724e5',
//   //   messagingSenderId: '653542564864',
//   //   projectId: 'dss-crm-f4669',
//   //   storageBucket: 'dss-crm-f4669.firebasestorage.app',
//   //   iosBundleId: 'com.codecrafter.dsscrm',
//   // );
//   //
//   // static const FirebaseOptions windows = FirebaseOptions(
//   //   apiKey: 'AIzaSyBMj9gHTStt99bM0fwjM1JtCF5xx--B3J4',
//   //   appId: '1:653542564864:web:52804166a3f952a8c724e5',
//   //   messagingSenderId: '653542564864',
//   //   projectId: 'dss-crm-f4669',
//   //   authDomain: 'dss-crm-f4669.firebaseapp.com',
//   //   storageBucket: 'dss-crm-f4669.firebasestorage.app',
//   //   measurementId: 'G-MMN2MY6H4H',
//   // );
// }
